<?php
require_once "functions.php";
if($_SERVER["REQUEST_METHOD"]=="POST")
{
    if(isset($_POST["add"]))
    {
        if($_POST["task"]!=null)
        {
            add_todos($_POST["task"]);
        }
    }
    elseif(isset($_POST["checked"]))
    {
        status_update($_POST["checked"]);
    }
    elseif(isset($_POST["deleted"]))
    {
       delete_todos($_POST["deleted"]);
    }
    elseif(isset($_POST["updated"]))
    {
        update_todos($_POST["updated"]);
    }
    elseif(isset($_POST["marked"]))
    {
        mark_as_important($_POST["marked"]);
    }
    elseif(isset($_POST["marked_off"]))
    {
        unmark($_POST["marked_off"]);
    }
    header("Location:todo.php");
}
